import type { UserRole } from "@/types/models";

export const PERMISSIONS = {
  // Stock Mutations
  STOCK_RECEIVE: "stock.receive",
  STOCK_ISSUE: "stock.issue",
  STOCK_MOVE: "stock.move",
  STOCK_TRANSFER_CREATE: "stock.transfer.create",
  STOCK_TRANSFER_COMPLETE: "stock.transfer.complete",
  STOCK_TRANSFER_CANCEL: "stock.transfer.cancel",
  STOCK_REVERSE: "stock.reverse",
  STOCK_COUNT: "stock.count",
  STOCK_COUNT_APPROVE: "stock.count.approve",

  // Stock Read Operations
  STOCK_VIEW: "stock.view",
  DOCUMENT_VIEW: "document.view",
  DOCUMENT_APPROVE: "document.approve",
  DOCUMENT_REJECT: "document.reject",

  // Master Data & Administration
  PRODUCT_MANAGE: "product.manage",
  LOCATION_MANAGE: "location.manage",
  WAREHOUSE_MANAGE: "warehouse.manage",
  USER_MANAGE: "user.manage",
  AUDIT_VIEW: "audit.view",
  RECOVERY_MANAGE: "recovery.manage",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

// Role to Permission Matrix (Strict Principle of Least Privilege)
export const ROLE_PERMISSION_MATRIX: Record<UserRole, readonly Permission[]> = {
  ADMIN: [
    PERMISSIONS.STOCK_RECEIVE,
    PERMISSIONS.STOCK_ISSUE,
    PERMISSIONS.STOCK_MOVE,
    PERMISSIONS.STOCK_TRANSFER_CREATE,
    PERMISSIONS.STOCK_TRANSFER_COMPLETE,
    PERMISSIONS.STOCK_TRANSFER_CANCEL,
    PERMISSIONS.STOCK_REVERSE,
    PERMISSIONS.STOCK_COUNT,
    PERMISSIONS.STOCK_COUNT_APPROVE,
    PERMISSIONS.STOCK_VIEW,
    PERMISSIONS.DOCUMENT_VIEW,
    PERMISSIONS.DOCUMENT_APPROVE,
    PERMISSIONS.DOCUMENT_REJECT,
    PERMISSIONS.PRODUCT_MANAGE,
    PERMISSIONS.LOCATION_MANAGE,
    PERMISSIONS.WAREHOUSE_MANAGE,
    PERMISSIONS.USER_MANAGE,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.RECOVERY_MANAGE,
  ],
  MANAGER: [
    PERMISSIONS.STOCK_RECEIVE,
    PERMISSIONS.STOCK_ISSUE,
    PERMISSIONS.STOCK_MOVE,
    PERMISSIONS.STOCK_TRANSFER_CREATE,
    PERMISSIONS.STOCK_TRANSFER_COMPLETE,
    PERMISSIONS.STOCK_TRANSFER_CANCEL,
    PERMISSIONS.STOCK_REVERSE,
    PERMISSIONS.STOCK_COUNT,
    PERMISSIONS.STOCK_COUNT_APPROVE,
    PERMISSIONS.STOCK_VIEW,
    PERMISSIONS.DOCUMENT_VIEW,
    PERMISSIONS.PRODUCT_MANAGE,
    PERMISSIONS.LOCATION_MANAGE,
    PERMISSIONS.AUDIT_VIEW,
  ],
  WAREHOUSE_STAFF: [
    PERMISSIONS.STOCK_RECEIVE,
    PERMISSIONS.STOCK_ISSUE,
    PERMISSIONS.STOCK_MOVE,
    PERMISSIONS.STOCK_TRANSFER_CREATE,
    PERMISSIONS.STOCK_TRANSFER_COMPLETE,
    PERMISSIONS.STOCK_TRANSFER_CANCEL,
    PERMISSIONS.STOCK_COUNT,
    PERMISSIONS.STOCK_VIEW,
    PERMISSIONS.DOCUMENT_VIEW,
  ],
  STAFF: [
    PERMISSIONS.STOCK_RECEIVE,
    PERMISSIONS.STOCK_ISSUE,
    PERMISSIONS.STOCK_MOVE,
    PERMISSIONS.STOCK_TRANSFER_CREATE,
    PERMISSIONS.STOCK_TRANSFER_COMPLETE,
    PERMISSIONS.STOCK_TRANSFER_CANCEL,
    PERMISSIONS.STOCK_VIEW,
    PERMISSIONS.DOCUMENT_VIEW,
  ],
  VIEWER: [
    PERMISSIONS.STOCK_VIEW,
    PERMISSIONS.DOCUMENT_VIEW,
  ],
};
